Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.FirearmsLicenseCheck = true -- Whether a arms dealer checks for a firearms license
Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}
Config.Products = {
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 23,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 10,
            amount = 99,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 9,
            amount = 99,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 8,
            amount = 99,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 8,
            amount = 99,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 26,
            amount = 99,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 18,
            amount = 99,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 24,
            amount = 99,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 23,
            amount = 99,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 250,
            amount = 99,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 3,
            amount = 99,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "rolling_paper",
            price = 4,
            amount = 999,
            info = {},
            type = "item",
            slot = 12,
        },
    },
    ["liquor"] = {
        [1] = {
            name = "beer",
            price = 7,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 10,
            amount = 99,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 12,
            amount = 99,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "lighter",
            price = 20,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "rolling_paper",
            price = 2,
            amount = 999,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "bandage",
            price = 2,
            amount = 99,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "ifaks", 
            price = 2,
            amount = 99,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "painkillers",
            price = 2,
            amount = 99,
            info = {},
            type = "item",
            slot = 8,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 1250,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 2500,
            amount = 9,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 2500,
            amount = 9,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "repairkit",
            price = 500,
            amount = 99,
            info = {},
            type = "item",
            slot = 4,
            requiredJob = { "mechanic", "police" }
        },
        [5] = {
            name = "screwdriverset",
            price = 400,
            amount = 99,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "phone",
            price = 2500,
            amount = 99,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "radio",
            price = 1000,
            amount = 99,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "binoculars",
            price = 250,
            amount = 9,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "fitbit",
            price = 400,
            amount = 9,
            info = {},
            type = "item",
            slot = 13,
        },
        [10] = {
            name = "cleaningkit",
            price = 150,
            amount = 99,
            info = {},
            type = "item",
            slot = 14,
        },
        [11] = {
            name = "advancedrepairkit",
            price = 500,
            amount = 99,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = { "mechanic" }
        },
        [12] = {
            name = "screwdriver",
            price = 250,
            amount = 99,
            info = {},
            type = "item",
            slot = 16,
        },
        [13] = {
            name = "wd40",
            price = 40,
            amount = 99,
            info = {},
            type = "item",
            slot = 17,
        },
        [14] = {
            name = "blowtorch",
            price = 1000,
            amount = 99,
            info = {},
            type = "item",
            slot = 18,
        },
        [15] = {
            name = "weapon_battleaxe",
            price = 5000,
            amount = 9,
            info = {},
            type = "item",
            slot = 19,
        },		
    },
    ["weedshop"] = {
        [1] = {
            name = "joint",
            price = 600,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weed_nutrition",
            price = 20,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "empty_weed_bag",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "rolling_paper",
            price = 2,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "parachute",
            price = 25000,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    -- ["leisureshop"] = {
    --     [1] = {
    --         name = "parachute",
    --         price = 25000,
    --         amount = 10,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [2] = {
    --         name = "binoculars",
    --         price = 250,
    --         amount = 50,
    --         info = {},
    --         type = "item",
    --         slot = 2,
    --     },
    --     [3] = {
    --         name = "diving_gear",
    --         price = 2500,
    --         amount = 10,
    --         info = {},
    --         type = "item",
    --         slot = 3,
    --     },
    --     [4] = {
    --         name = "diving_fill",
    --         price = 500,
    --         amount = 10,
    --         info = {},
    --         type = "item",
    --         slot = 4,
    --     },
    --     -- [4] = {
    --     --     name = "smoketrailred",
    --     --     price = 250,
    --     --     amount = 50,
    --     --     info = {},
    --     --     type = "item",
    --     --     slot = 4,
    --     -- },
    -- },
    ["weapons"] = {
        [1] = {
            name = "weapon_knife",
            price = 3500,
            amount = 250,
            info = {},
            type = "item",
            slot = 1,
            --requiredJob = { "police" }
        },
        [2] = {
            name = "weapon_bat",
            price = 7500,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
            --requiredJob = { "police" }
        },
        [3] = {
            name = "weapon_battleaxe",
            price = 5000,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
            --requiredJob = { "police" }
        },
        [4] = {
            name = "weapon_pistol",
            price = 10000,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
            requiresLicense = true
        },
        [5] = {
            name = "weapon_snspistol",
            price = 5000,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
            requiresLicense = true
        },
        [6] = {
            name = "weapon_pistol_mk2",
            price = 25000,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
            requiresLicense = true
        },
        [7] = {
            name = "pistol_ammo",
            price = 500,
            amount = 99,
            info = {},
            type = "item",
            slot = 7,
            requiresLicense = true
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
    ["lumber"] = {
        [1] = {
            name = 'weapon_battleaxe',
            price = 2500,
            amount = 99,
            info = {},
            type = 'weapon',
            slot = 1,
        }
    },
    ["huntingshop"] = {
        [1] = {
            name = 'weapon_huntingrifle',
            price = 5000,
            amount = 99,
            info = {},
            type = 'weapon',
            slot = 1,
            --requiresLicense = false
        },
        [2] = {
            name = 'huntingbait',
            price = 100,
            amount = 9999,
            info = {},
            type = 'item',
            slot = 2
        },
        [3] = {
            name = 'weapon_knife',
            price = 1500,
            amount = 99,
            info = {},
            type = 'item',
            slot = 3
        }
    },
    ["burgershot"] = {
        [1] = {
            name = 'burger-bleeder',
            price = 1500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'burger-meatfree',
            price = 100,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'burger-fries',
            price = 150,
            amount = 150,
            info = {},
            type = 'item',
            slot = 3
        },
        [4] = {
            name = 'burger-softdrink',
            price = 500,
            amount = 50,
            info = {},
            type = 'item',
            slot = 4
        },
        [5] = {
            name = 'burger-softdrink',
            price = 500,
            amount = 50,
            info = {},
            type = 'item',
            slot = 5
        }
    },
    ["electric"] = {
        [1] = {
            name = "phone",
            price = 2500,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "radio",
            price = 1000,
            amount = 99,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "fitbit",
            price = 500,
            amount = 99,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["shadycrim"] = {
        [1] = {
            name = "lockpick",
            price = 250,
            amount = 99,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "laptop",
            price = 10000,
            amount = 9,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "pistol_ammo",
            price = 500,
            amount = 99,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "joint",
            price = 250,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weed_nutrition",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "advancedlockpick",
            price = 2500,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "hydrochloric_acid",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "trimming_scissors",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "finescale",
            price = 250,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "sodium_hydroxide",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        },
    },
}
Config.Locations = {
    ["shadycrim"] = {
        ["label"] = "Shady Criminal",
        ["coords"] = vector4(-3058.81, 142.0, 11.61, 265.78),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Talk to the Shady Criminal",
        ["products"] = Config.Products["shadycrim"],
        ["showblip"] = true,
        ["blipsprite"] = 205,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },
    ["electric"] = {
        ["label"] = "Electronic Shop",
        ["coords"] = vector4(1138.06, -470.96, 66.66, 255.84),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Electronic Shop",
        ["products"] = Config.Products["electric"],
        ["showblip"] = true,
        ["blipsprite"] = 354,
        ["blipscale"] = 0.9,
        ["blipcolor"] = 0
    },
    ["electric]"] = {
        ["label"] = "Electronic Shop",
        ["coords"] = vector4(-1525.32, -410.89, 35.59, 228.2),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Electronic Shop",
        ["products"] = Config.Products["electric"],
        ["showblip"] = true,
        ["blipsprite"] = 354,
        ["blipscale"] = 0.9,
        ["blipcolor"] = 0
    },
    ["electric]"] = {
        ["label"] = "Electronic Shop",
        ["coords"] = vector4(-1183.35, -1243.97, 7.01, 108.33),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Electronic Shop",
        ["products"] = Config.Products["electric"],
        ["showblip"] = true,
        ["blipsprite"] = 354,
        ["blipscale"] = 0.9,
        ["blipcolor"] = 0
    },
    ["electric]"] = {
        ["label"] = "Electronic Shop",
        ["coords"] = vector4(-530.91, -854.72, 29.8, 356.94),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Electronic Shop",
        ["products"] = Config.Products["electric"],
        ["showblip"] = true,
        ["blipsprite"] = 354,
        ["blipscale"] = 0.9,
        ["blipcolor"] = 0
    },
    ["burgershot"] = {
        ["label"] = "Burgershot",
        ["coords"] = vector4(-1193.85, -895.8, 14.0, 301.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Burgershot",
        ["products"] = Config.Products["burgershot"],
        ["showblip"] = false,
        ["blipsprite"] = 626,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1
    },
    ["lumber"] = {
        ["label"] = "Ryker's Lumberyard Shop",
        ["coords"] = vector4(-570.32, 5309.59, 73.6, 55.8),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Lumberyard Shop",
        ["products"] = Config.Products["lumber"],
        ["showblip"] = true,
        ["blipsprite"] = 605,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 69
    },
    ["huntingshop"] = {
        ["label"] = "Hunting Shop",
        ["coords"] = vector4(-679.47, 5834.49, 17.33, 127.62),
        ["ped"] = 'ig_hunter',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Hunting Shop",
        ["products"] = Config.Products["huntingshop"],
        ["showblip"] = true,
        ["blipsprite"] = 141,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1
    },
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket2"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket3"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket4"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket5"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket6"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket7"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket8"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket9"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline2"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline3"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline4"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline5"] = {
        ["label"] = "Supermarket",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipscale"] = 0.55,
        ["blipcolor"] = 0
    },

    ["robsliquor2"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 51,
        ["blipscale"] = 0.55,
        ["blipcolor"] = 0
    },

    ["robsliquor3"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 51,
        ["blipscale"] = 0.55,
        ["blipcolor"] = 0
    },

    ["robsliquor4"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 51,
        ["blipscale"] = 0.55,
        ["blipcolor"] = 0
    },

    ["robsliquor5"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 51,
        ["blipscale"] = 0.55,
        ["blipcolor"] = 0
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["hardware4"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-1377.55, -361.29, 36.62, 170.7),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 156,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 37
    },

    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(949.29, 32.13, 71.95, 79.54),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = true,
        ["blipsprite"] = 674,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(937.45, 27.22, 71.83, 61.21),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1172.44, -1573.87, 4.66, 92.59),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 3.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 2
    },

    -- Sea Word Locations
    ["seaword"] = {
        ["label"] = "Diving Store",
        ["coords"] = vector4(-1791.88, -994.6, 2.41, 79.56),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish",
        ["targetLabel"] = "Diving Store",
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = true,
        ["blipsprite"] = 597,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 3
    },

    -- Leisure Shop Locations
    -- ["leisureshop"] = {
    --     ["label"] = "Leisure Shop",
    --     ["coords"] = vector4(-1505.91, 1511.95, 115.29, 257.13),
    --     ["ped"] = 'a_m_y_beach_01',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-leaf",
    --     ["targetLabel"] = "Open Leisure Shop",
    --     ["products"] = Config.Products["leisureshop"],
    --     ["showblip"] = true,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.7,
    --     ["blipcolor"] = 0
    -- },
}
